"""empty message

Revision ID: 16254a6815bf
Revises: 389077184ae1
Create Date: 2016-02-29 17:21:36.463309

"""

# revision identifiers, used by Alembic.
revision = '16254a6815bf'
down_revision = '389077184ae1'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('area', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=False))
    op.drop_column('block', 'polygon')
    op.add_column('lot', sa.Column('lot_area', sa.String(length=10), nullable=True))
    op.alter_column('lot', 'area',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('lot', 'polygon')
    op.add_column('section', sa.Column('area', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=False))
    op.drop_column('section', 'polygon')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('polygon', geoalchemy2.types.Geometry(geometry_type=u'POLYGON'), autoincrement=False, nullable=False))
    op.drop_column('section', 'area')
    op.add_column('lot', sa.Column('polygon', geoalchemy2.types.Geometry(geometry_type=u'POLYGON'), autoincrement=False, nullable=False))
    op.alter_column('lot', 'area',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('lot', 'lot_area')
    op.add_column('block', sa.Column('polygon', geoalchemy2.types.Geometry(geometry_type=u'POLYGON'), autoincrement=False, nullable=False))
    op.drop_column('block', 'area')
    ### end Alembic commands ###
