"""empty message

Revision ID: 259637f40381
Revises: 53aa2b250c41
Create Date: 2016-07-02 23:37:01.934871

"""

# revision identifiers, used by Alembic.
revision = '259637f40381'
down_revision = '53aa2b250c41'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crematorium', 'deceased_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crematorium', 'deceased_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
