"""empty message

Revision ID: 26b7fdc4ebdb
Revises: 5354c80cd46b
Create Date: 2016-06-07 00:44:43.831798

"""

# revision identifiers, used by Alembic.
revision = '26b7fdc4ebdb'
down_revision = '5354c80cd46b'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crematorium', 'gender')
    op.drop_column('crematorium', 'first_name')
    op.drop_column('crematorium', 'last_name')
    op.drop_column('crematorium', 'middle_name')
    op.drop_column('crematorium', 'date_of_birth')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crematorium', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('crematorium', sa.Column('middle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('crematorium', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('crematorium', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('crematorium', sa.Column('gender', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    ### end Alembic commands ###
