"""empty message

Revision ID: 29a97d2201be
Revises: b811b342d63
Create Date: 2016-06-07 15:05:29.442948

"""

# revision identifiers, used by Alembic.
revision = '29a97d2201be'
down_revision = 'b811b342d63'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crematorium', 'date_cremated',
               existing_type=sa.DATE(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crematorium', 'date_cremated',
               existing_type=sa.DATE(),
               nullable=True)
    ### end Alembic commands ###
