"""empty message

Revision ID: 328ae18bcf8c
Revises: 236a25eaea73
Create Date: 2016-04-29 00:17:50.815261

"""

# revision identifiers, used by Alembic.
revision = '328ae18bcf8c'
down_revision = '236a25eaea73'

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('dimension', sa.String(), nullable=True))
    op.drop_column('lot', 'dimension_height')
    op.drop_column('lot', 'dimension_width')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('dimension_width', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('lot', sa.Column('dimension_height', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('lot', 'dimension')
    ### end Alembic commands ###
