"""empty message

Revision ID: 389077184ae1
Revises: 43d7f8bcbf97
Create Date: 2016-02-29 16:28:12.436552

"""

# revision identifiers, used by Alembic.
revision = '389077184ae1'
down_revision = '43d7f8bcbf97'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_column('lot', 'remarks')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('remarks', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('lot', 'status')
    ### end Alembic commands ###
