"""empty message

Revision ID: 404e508ccf91
Revises: 328ae18bcf8c
Create Date: 2016-05-19 01:10:44.691417

"""

# revision identifiers, used by Alembic.
revision = '404e508ccf91'
down_revision = '328ae18bcf8c'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('columbary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('c_no', sa.Integer(), nullable=True),
    sa.Column('block', sa.String(length=1), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('date_purchased', sa.Date(), nullable=True),
    sa.Column('or_no', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_columbary_status'), 'columbary', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_columbary_status'), table_name='columbary')
    op.drop_table('columbary')
    ### end Alembic commands ###
