"""empty message

Revision ID: 4072f2985ba4
Revises: 11d1df1a1979
Create Date: 2016-06-01 02:22:32.262767

"""

# revision identifiers, used by Alembic.
revision = '4072f2985ba4'
down_revision = '11d1df1a1979'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('gender', sa.String(length=6), nullable=True))
    op.add_column('deceased', sa.Column('gender', sa.String(length=6), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deceased', 'gender')
    op.drop_column('client', 'gender')
    ### end Alembic commands ###
