"""empty message

Revision ID: 42eafc87e7e
Revises: 44ca10988e54
Create Date: 2016-03-08 23:41:14.946747

"""

# revision identifiers, used by Alembic.
revision = '42eafc87e7e'
down_revision = '44ca10988e54'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lot', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lot', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
