"""empty message

Revision ID: 4c723db98d5e
Revises: 42eafc87e7e
Create Date: 2016-03-09 00:26:50.171824

"""

# revision identifiers, used by Alembic.
revision = '4c723db98d5e'
down_revision = '42eafc87e7e'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('dimension_height', sa.Float(), nullable=True))
    op.add_column('lot', sa.Column('dimension_width', sa.Float(), nullable=True))
    op.drop_column('lot', 'dimension')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('dimension', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('lot', 'dimension_width')
    op.drop_column('lot', 'dimension_height')
    ### end Alembic commands ###
