"""empty message

Revision ID: 4e408282fc03
Revises: 56c96ab94f02
Create Date: 2016-04-02 19:09:53.763996

"""

# revision identifiers, used by Alembic.
revision = '4e408282fc03'
down_revision = '56c96ab94f02'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lot', 'or_no')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('or_no', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    ### end Alembic commands ###
