"""empty message

Revision ID: 5354c80cd46b
Revises: 5ab28d3f1722
Create Date: 2016-06-01 02:52:28.063630

"""

# revision identifiers, used by Alembic.
revision = '5354c80cd46b'
down_revision = '5ab28d3f1722'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crematorium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('deceased_id', sa.Integer(), nullable=False),
    sa.Column('date_cremated', sa.Date(), nullable=True),
    sa.Column('datetime_started', sa.DateTime(), nullable=True),
    sa.Column('datetime_finished', sa.DateTime(), nullable=True),
    sa.Column('gas_consumed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['deceased_id'], ['deceased.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crematorium_deceased_id'), 'crematorium', ['deceased_id'], unique=False)
    op.create_index(op.f('ix_crematorium_first_name'), 'crematorium', ['first_name'], unique=False)
    op.create_index(op.f('ix_crematorium_last_name'), 'crematorium', ['last_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crematorium_last_name'), table_name='crematorium')
    op.drop_index(op.f('ix_crematorium_first_name'), table_name='crematorium')
    op.drop_index(op.f('ix_crematorium_deceased_id'), table_name='crematorium')
    op.drop_table('crematorium')
    ### end Alembic commands ###
