"""empty message

Revision ID: 53aa2b250c41
Revises: 29a97d2201be
Create Date: 2016-07-02 20:33:30.357347

"""

# revision identifiers, used by Alembic.
revision = '53aa2b250c41'
down_revision = '29a97d2201be'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funeral_homes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('crematorium', sa.Column('funeral_home_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crematorium', 'funeral_homes', ['funeral_home_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crematorium', type_='foreignkey')
    op.drop_column('crematorium', 'funeral_home_id')
    op.drop_table('funeral_homes')
    ### end Alembic commands ###
