"""empty message

Revision ID: 56c96ab94f02
Revises: 4c723db98d5e
Create Date: 2016-03-22 21:47:02.577966

"""

# revision identifiers, used by Alembic.
revision = '56c96ab94f02'
down_revision = '4c723db98d5e'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('or_no', sa.String(length=10), nullable=True))
    op.add_column('lot', sa.Column('remarks', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lot', 'remarks')
    op.drop_column('lot', 'or_no')
    ### end Alembic commands ###
