"""empty message

Revision ID: 58e178fe71a8
Revises: 404e508ccf91
Create Date: 2016-05-22 23:27:08.251132

"""

# revision identifiers, used by Alembic.
revision = '58e178fe71a8'
down_revision = '404e508ccf91'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columbary', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_columbary_client_id'), 'columbary', ['client_id'], unique=False)
    op.create_foreign_key(None, 'columbary', 'client', ['client_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'columbary', type_='foreignkey')
    op.drop_index(op.f('ix_columbary_client_id'), table_name='columbary')
    op.drop_column('columbary', 'client_id')
    ### end Alembic commands ###
