"""empty message

Revision ID: 7905224ce74
Revises: 58e178fe71a8
Create Date: 2016-05-30 17:35:07.964736

"""

# revision identifiers, used by Alembic.
revision = '7905224ce74'
down_revision = '58e178fe71a8'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deceased_occupancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deceased_id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('ref_table', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['deceased_id'], ['deceased.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deceased_occupancy_deceased_id'), 'deceased_occupancy', ['deceased_id'], unique=False)
    op.drop_constraint(u'deceased_lot_id_fkey', 'deceased', type_='foreignkey')
    op.drop_column('deceased', 'lot_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deceased', sa.Column('lot_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'deceased_lot_id_fkey', 'deceased', 'lot', ['lot_id'], ['id'])
    op.drop_index(op.f('ix_deceased_occupancy_deceased_id'), table_name='deceased_occupancy')
    op.drop_table('deceased_occupancy')
    ### end Alembic commands ###
