"""empty message

Revision ID: b811b342d63
Revises: 26b7fdc4ebdb
Create Date: 2016-06-07 14:45:12.512834

"""

# revision identifiers, used by Alembic.
revision = 'b811b342d63'
down_revision = '26b7fdc4ebdb'

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crematorium', sa.Column('time_finished', sa.String(), nullable=False))
    op.add_column('crematorium', sa.Column('time_started', sa.String(), nullable=False))
    op.drop_column('crematorium', 'datetime_finished')
    op.drop_column('crematorium', 'datetime_started')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crematorium', sa.Column('datetime_started', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('crematorium', sa.Column('datetime_finished', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('crematorium', 'time_started')
    op.drop_column('crematorium', 'time_finished')
    ### end Alembic commands ###
