"""empty message

Revision ID: eb6a53c023a
Revises: 42937d3d2c37
Create Date: 2016-04-23 19:12:16.956812

"""

# revision identifiers, used by Alembic.
revision = 'eb6a53c023a'
down_revision = '42937d3d2c37'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('name', sa.String(length=5), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lot', 'name')
    ### end Alembic commands ###
